### ISSUE TITLE
Error <style scoped> ^

### ISSUE THREAD

**Issue by nacr-dev** [hilongjw/vue-progressbar#10]
Hello,

First tks for your work :)

I get this error:

```
<style scoped>
^
```

When I run Gulp.

**Comment by nacr-dev** [comment]
@hilongjw I'm using browserify and vue@1.0.26

**Comment by nacr-dev** [comment]
No Help Here???

**Comment by hilongjw** [comment]
@nacr-dev sorry. I use webpack . Is browserify not support vue style scoped?

**Comment by nacr-dev** [comment]
@hilongjw I can't say that.

**Comment by nacr-dev** [comment]
But I can't find any other reason for this, it wouldn't be the first time that I was wrong!

**Comment by hilongjw** [comment]
@nacr-dev  I has removed scope style in new version

**Comment by nacr-dev** [comment]
@hilongjw sorry I'm having the same problem with the new version.

**Comment by ktquez** [comment]
@nacr 
Me too!

**Comment by frankbaele** [comment]
Somewhere i read that vueify or browserify-css doesn't like vue/css files from node_modules. 
You have to link to them directly if vueify/browserify-css needs to parse them.

e.g. => works for me.

var VueProgressBar = require('../../node_modules/vue-progressbar/vue-progressbar.es5.js');
