### ISSUE TITLE
 Error when evaluating expression

### ISSUE THREAD

**Issue by mahdisyazdani** [hilongjw/vue-progressbar#11]
i follow the documentation but i have this error:

> vue.common.js?e881:1019[Vue warn]: Error when evaluating expression "{
>   'width': progress.percent+'%',
>   'height': progress.options.height,
>   'background-color': progress.options.canSuccess? progress.options.color : progress.options.failedColor,
>   'opacity': progress.options.show ? 1 : 0
> }": TypeError: Cannot read property 'percent' of undefined (found in component: <vue-progress-bar>)

**Comment by hilongjw** [comment]
@mahdisyazdani need live repo or you can see this example https://github.com/hilongjw/vue-progress-dev/tree/master/client/index

**Comment by sebastiansson** [comment]
I was having the same problem as @mahdisyazdani in version 0.4.0. I'm using Vue-version v1.0.28. The link to your progress-dev works for me but uses other dependencies, like Vue 2. Now I get this error instead on version 0.4.1. Maybe vue-router related?
<img width="1123" alt="skarmavbild 2016-10-06 kl 09 35 07" src="https://cloud.githubusercontent.com/assets/3044878/19144189/7c68ad88-8ba8-11e6-8ec7-71127c19e274.png">

**Comment by hilongjw** [comment]
@sebastiansson I has tested in my Vue2 and VueRouter2 project, it's work fine.

**Comment by hilongjw** [comment]
@sebastiansson Run vm.$Progress.start() when vue app initializing will got this problem, I'll fix it soon.

**Comment by hilongjw** [comment]
@sebastiansson @mahdisyazdani  try update vue-progressbar to 0.5.0, I use eventbus instead of to rewrite instance data function

**Comment by djshox** [comment]
cannot read property '$Progress' of undefined?
