### ISSUE TITLE
support vue.js 2.0

### ISSUE THREAD

**Issue by lsxiao** [hilongjw/vue-progressbar#12]
any plan to support vue.js 2.0?

**Comment by Towerful** [comment]
How does this not support Vue 2.0?

**Comment by Towerful** [comment]
Ah,  
Seems to be a problem in the way it binds.  
I wish I knew more about plugins. I've had a fiddle, looked at other plugins.  
Its a mystery to me :(

**Comment by hilongjw** [comment]
@lsxiao because it's not recommend that adding reactive properties to a Vue root instance $data  at runtime Vue 2.0, I'm trying to find an easy way like current usage.

**Comment by hilongjw** [comment]
@lsxiao It's  support Vue.js 2.0 now.

**Comment by Towerful** [comment]
Wow, awesome!   
Just tested, and looking great. Thanks.
