### ISSUE TITLE
Error when rendering component <vue-progress-bar>:

### ISSUE THREAD

**Issue by davidpmtz** [hilongjw/vue-progressbar#14]
HI, I got this error when I use Vuex to declare something like this `const store = new Vuex.Store({})`, why?

**Comment by hilongjw** [comment]
There is no relationship between Vuex and vue-progressbar...

**Comment by davidpmtz** [comment]
Yeah, but I don't know why but it works if I first declare the `const `and after `Vue.use(VueProgressBar, {})` otherwise still appears the error.
