### ISSUE TITLE
Feature Request: Pause Progress

### ISSUE THREAD

**Issue by kJamesy** [hilongjw/vue-progressbar#15]
Hi,
I have some use-cases for when a task takes quite a bit of time and the progress bar gets to the end before the task is actually complete and before I have asked it to $Progress.finish().
Could we possibly pause it at say a certain percentage for such cases and then finish it upon completion of task?

**Comment by ilongley** [comment]
You could use this.$Progress.set(num) perhaps?

**Comment by kJamesy** [comment]
That just begins the growth of the bar at the set percentage as opposed to doing quite the opposite - pausing the growth at a certain percentage.

**Comment by ilongley** [comment]
in vue-progressbar.js add this function -

pause () {
  this.$root.RADON_LOADING_BAR.percent = this.$root.RADON_LOADING_BAR.percent
  clearInterval(this.state.timer)
},

and in the existing start() function, change the line -

this.$root.RADON_LOADING_BAR.percent = 0

to

this.$root.RADON_LOADING_BAR.percent = this.$root.RADON_LOADING_BAR.percent

Hopefully that helps.

**Comment by hilongjw** [comment]
Thanks for @ilongley 's pr

**Comment by kJamesy** [comment]
Many thanks for this. Any chance of updating the NPM package?

**Comment by hilongjw** [comment]
@kJamesy I just updated it.

**Comment by kJamesy** [comment]
Working perfectly, many thanks!
