### ISSUE TITLE
Uglify Error

### ISSUE THREAD

**Issue by GeoffZhu** [hilongjw/vue-progressbar#18]
File vue-progressbar.es5.js

<img width="421" alt="2016-11-02 3 07 35" src="https://cloud.githubusercontent.com/assets/10768286/19919487/1d1f0fb8-a10e-11e6-9f73-a2f03b76e85d.png">

This is ES6 feature，make Uglify SyntaxError

**Comment by hilongjw** [comment]
@GeoffZhu thanks, I will fix soon

**Comment by GeoffZhu** [comment]
thx，想问一下，为什么要把每个function写成
`init: function init(vm) {}`

  ##正常情况下不是吗？
`init: function (vm) {}`

**Comment by hilongjw** [comment]
@GeoffZhu `vue-progressbar.es5.js` 是通过babel编译生成的

**Comment by GeoffZhu** [comment]
@hilongjw 懂了，多谢🙏，看过你的很多代码，收获多多。best wishes

**Comment by hilongjw** [comment]
@GeoffZhu 😀一起加油！
