### ISSUE TITLE
Does not support IE11 as well as part of the Android mobile phone

### ISSUE THREAD

**Issue by jslygljy** [hilongjw/vue-progressbar#26]
The report does not support ‘assign’ features

**Comment by simzen85** [comment]
+1

Is there any quick way to fix this ? Thanks.

**Comment by jslygljy** [comment]
in vue-progressbar.js 212 line 
progressOptions = Object.assign(DEFAULT_OPTION, options);
If you can rewrite this method should be able to
Assign this API does not support IE

**Comment by hilongjw** [comment]
@jslygljy @simzen85 fix @0.7.1
