### ISSUE TITLE
The progressbar animation doesn't stop.

### ISSUE THREAD

**Issue by thulioph** [hilongjw/vue-progressbar#45]
After using the method `this.$Progressbar.finish()`, the animation doesn't stop and it's my problem when I use your library.

You can see the image for more details: http://d.pr/i/qivNC.

Thank you for working on porting the progressbar to use with Vue.

**Comment by tsalpekar21** [comment]
Same problem for me too :/

**Comment by dneukirchen** [comment]
Same issue here.

**Comment by HKskn** [comment]
you should use  - this.$Progress.finish()

**Comment by AlbinoDrought** [comment]
In `$Progress.start()`, the `state.timer` is being overwritten with a new call to setInterval.

This prevents the old setInterval call from being cleared, causing it to update forever.

I've submitted a pull request that fixes this issue at https://github.com/hilongjw/vue-progressbar/pull/50
