### ISSUE TITLE
when finish looks like is rollback

### ISSUE THREAD

**Issue by c941010623** [hilongjw/vue-progressbar#48]
in vue2 when finish then the progress will from 100 to 0
so will looks like is rollback (100 99 98 97 ..... 0)

can you first window.VueProgressBarEventBus.RADON_LOADING_BAR.options.show=false
then run your this.$vm.RADON_LOADING_BAR.percent = 0

i think this is good work for us thanks~~

**Comment by javascripet** [comment]
"looks like is rollback"
i found it too

**Comment by c941010623** [comment]
so~~~
who can help ?
