### ISSUE TITLE
Using start() and finish() on vuex axios call

### ISSUE THREAD

**Issue by sergiocastrovale** [hilongjw/vue-progressbar#52]
Doing something like this won't work, since we don't have the context ("this") inside vuex:

    login: ({ commit }, data) => {
        this.$Progress.start();

        axios.post('auth/login', params).then((response) => {
            if (response.status === 200) {
                this.$Progress.finish();
            }
        })
        .catch((error) => {
            console.log(error);
        });
    },

As using vuex and axios is becoming more and more the de facto standard for medium and large applications, it would be a deal breaker if we couldn't do something like this. Is there any solution that doesn't involve "hacking it" by emitting events?

**Comment by rodrigoAbril** [comment]
please?

**Comment by johndatserakis** [comment]
Hey there - here's what I do in an app of mine - works great - although it's a different take on the same goal (from what I can see). Basically, instead of running the vue-progressbar manually on each request, I set the action up using [axios interceptors](https://github.com/mzabriskie/axios#interceptors) - so it runs automatically. Works pretty seamlessly - even for errors -  and hasn't caused any issues. Here's the [repo](https://github.com/johndatserakis/koa-vue-notes-web) and the [live demo](https://koa-vue-notes-web.innermonkdesign.com/) of the project. Note - I am using vue-router and grab the `$Progress` hook from there.

```javascript
//The following two interceptor blocks are strickly for
//attaching the top-loading bar to all axios requests and
//stoping the bar on all responses.
axios.interceptors.request.use(function (config) {
    router.app.$Progress.start()
    return config;
}, function (error) {
    router.app.$Progress.fail()
    return Promise.reject(error);
});
axios.interceptors.response.use(function (response) {
    router.app.$Progress.finish()
    return response;
}, function (error) {
    router.app.$Progress.fail()
    return Promise.reject(error);
});
```

**Comment by sergiocastrovale** [comment]
Hi @johndatserakis - thanks for this.

One question though: wouldn't this require two different bindings, one for axios requests and the other (possibly placed in App.vue) for regular component loading?

**Comment by johndatserakis** [comment]
Yuo - that's exactly right. In addition to the above code, my `router` file looks like this.

```
router.beforeEach((to, from, next) => {
    //Start our loading strip
    router.app.$Progress.start()
    next()
})

router.afterEach((to, from) => {
    //End our loading strip
    router.app.$Progress.finish()
})
```

And that's it - all components and api calls are handled without having to attach or detach anything.

**Comment by sergiocastrovale** [comment]
Great - I had reached more or less the same conclusions as you did @johndatserakis but thanks for sharing the code snippets. I guess this will solve the issue for anyone that bumps into it.

**Comment by BusyHe** [comment]
@sergiocastrovale i not use router，how can i use $Progress.start() in axios

**Comment by sergiocastrovale** [comment]
@BusyHe If you import Vue, you can prototype $Progress like this:

`Vue.prototype.$Progress.start()`

**Comment by rodrigoAbril** [comment]
@BusyHe if you use vuex you can triguer a state mutation in the axios interceptor similar at what @johndatserakis is doing, then in your app.vue you can trigger the progress bar start or stop actions based on that vuex state

**Comment by BusyHe** [comment]
@sergiocastrovale thanks, 666
