### ISSUE TITLE
Demo page still has precent typos

### ISSUE THREAD

**Issue by priithansen** [hilongjw/vue-progressbar#7]
precent => percent typos fixed in commit "2ab662423afa6208720fd0a75d717809296f65b0" are still visible on the demo page.

Thank You for the useful module!

**Comment by hilongjw** [comment]
Hi, @priithansen , thanks for you issue, I'll fix it

**Comment by hilongjw** [comment]
Hi, @priithansen , thanks for you issue, I'll fix it
