### ISSUE TITLE
naming convention

### ISSUE THREAD

**Issue by andre-dw** [hilongjw/vue-progressbar#8]
Isn't it better to name the methods:
`
this.$progress.finish()
this.$progress.failed()
`
like this:

`
this.$progress.finished()
this.$progress.failed()
`
or

`
this.$progress.finish()
this.$progress.fail()
`
To get a better naming convention

Plugin is great though.

**Comment by hilongjw** [comment]
@andre-dw Thanks, I'll update it soon
